// <auto-generated />
namespace EASHLWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_post_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_post_model));
        
        string IMigrationMetadata.Id
        {
            get { return "201508180853098_changed_post_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
